# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramics', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/ceramics/images/'),
        ),
    ]
